apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260527-135148-hi0tt5pb5p35-service
spec:
  selector:
    app: enterprise-system-20260527-135148-hi0tt5pb5p35
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
